import ROUTES from 'constants/routes';
import { ROLES } from 'types/roles';

export type ComponentTypes =
	| 'current_org_settings'
	| 'invite_members'
	| 'create_new_dashboards'
	| 'import_dashboard'
	| 'export_dashboard'
	| 'add_new_alert'
	| 'add_new_channel'
	| 'set_retention_period'
	| 'action'
	| 'save_layout'
	| 'edit_dashboard'
	| 'delete_widget'
	| 'new_dashboard'
	| 'new_alert_action'
	| 'edit_widget'
	| 'add_panel'
	| 'page_pipelines'
	| 'edit_locked_dashboard'
	| 'add_panel_locked_dashboard';

// Human-readable descriptions for component permissions
export const componentPermissionDescriptions: Record<ComponentTypes, string> = {
	current_org_settings: 'Access to organization-level settings and configuration',
	invite_members: 'Ability to invite new members to the organization',
	create_new_dashboards: 'Permission to create new dashboards',
	import_dashboard: 'Ability to import dashboards from external sources',
	export_dashboard: 'Permission to export dashboards',
	add_new_alert: 'Ability to create new alert rules',
	add_new_channel: 'Permission to add new notification channels',
	set_retention_period: 'Ability to configure data retention settings',
	action: 'General action permissions for alerts and notifications',
	save_layout: 'Permission to save dashboard layout changes',
	edit_dashboard: 'Ability to edit existing dashboards',
	delete_widget: 'Permission to delete widgets from dashboards',
	new_dashboard: 'Ability to create new dashboards',
	new_alert_action: 'Permission to create new alert actions',
	edit_widget: 'Ability to edit dashboard widgets',
	add_panel: 'Permission to add new panels to dashboards',
	page_pipelines: 'Access to data processing pipelines page',
	edit_locked_dashboard: 'Ability to edit locked/protected dashboards',
	add_panel_locked_dashboard: 'Permission to add panels to locked dashboards',
};

// Human-readable descriptions for route permissions
export const routePermissionDescriptions: Record<keyof typeof ROUTES, string> = {
	HOME: 'Access to the main dashboard and home page',
	ALERTS_NEW: 'Access to create new alert rules',
	ORG_SETTINGS: 'Access to organization-level settings and configuration',
	MY_SETTINGS: 'Access to personal user settings and preferences',
	SERVICE_MAP: 'Access to service dependency maps and topology',
	ALL_CHANNELS: 'Access to view all notification channels',
	INGESTION_SETTINGS: 'Access to data ingestion configuration',
	ALL_DASHBOARD: 'Access to view all dashboards',
	MESSAGING_QUEUES_KAFKA: 'Access to Kafka messaging queue monitoring',
	MESSAGING_QUEUES_KAFKA_DETAIL: 'Access to detailed Kafka queue information',
	ALL_ERROR: 'Access to error tracking and monitoring',
	APPLICATION: 'Access to application performance monitoring',
	CHANNELS_EDIT: 'Access to edit notification channels',
	CHANNELS_NEW: 'Access to create new notification channels',
	DASHBOARD: 'Access to individual dashboard views',
	DASHBOARD_WIDGET: 'Access to dashboard widget configuration',
	EDIT_ALERTS: 'Access to edit existing alert rules',
	ERROR_DETAIL: 'Access to detailed error information',
	HOME_PAGE: 'Access to the main home page',
	LIST_ALL_ALERT: 'Access to view all alert rules',
	ALERT_HISTORY: 'Access to alert history and logs',
	ALERT_OVERVIEW: 'Access to alert overview and summary',
	LOGIN: 'Access to login page',
	NOT_FOUND: 'Access to 404 error page',
	PASSWORD_RESET: 'Access to password reset functionality',
	SERVICE_METRICS: 'Access to service-level metrics and monitoring',
	SETTINGS: 'Access to general application settings',
	SIGN_UP: 'Access to user registration page',
	TRACES_EXPLORER: 'Access to distributed tracing explorer',
	TRACE: 'Access to individual trace views',
	TRACE_DETAIL: 'Access to detailed trace information',
	UN_AUTHORIZED: 'Access to unauthorized error page',
	USAGE_EXPLORER: 'Access to usage analytics and exploration',
	VERSION: 'Access to version information page',
	LOGS: 'Access to log management and viewing',
	LOGS_EXPLORER: 'Access to log exploration and search',
	LIVE_LOGS: 'Access to real-time log streaming',
	LIST_LICENSES: 'Access to license management',
	LOGS_INDEX_FIELDS: 'Access to log index field configuration',
	LOGS_PIPELINES: 'Access to log processing pipelines',
	TRACE_EXPLORER: 'Access to trace exploration and analysis',
	GET_STARTED: 'Access to onboarding and getting started guides',
	ONBOARDING: 'Access to initial setup and onboarding process',
	GET_STARTED_WITH_CLOUD: 'Access to cloud-specific onboarding',
	GET_STARTED_APPLICATION_MONITORING: 'Access to application monitoring setup',
	GET_STARTED_INFRASTRUCTURE_MONITORING: 'Access to infrastructure monitoring setup',
	GET_STARTED_LOGS_MANAGEMENT: 'Access to logs management setup',
	GET_STARTED_AWS_MONITORING: 'Access to AWS monitoring setup',
	GET_STARTED_AZURE_MONITORING: 'Access to Azure monitoring setup',
	WORKSPACE_LOCKED: 'Access to locked workspace page',
	WORKSPACE_SUSPENDED: 'Access to suspended workspace page',
	BILLING: 'Access to billing and payment information',
	SUPPORT: 'Access to support and help resources',
	SOMETHING_WENT_WRONG: 'Access to error handling page',
	LOGS_SAVE_VIEWS: 'Access to save and manage log views',
	TRACES_SAVE_VIEWS: 'Access to save and manage trace views',
	TRACES_FUNNELS: 'Access to trace funnel analysis',
	TRACES_FUNNELS_DETAIL: 'Access to detailed trace funnel information',
	API_KEYS: 'Access to API key management',
	CUSTOM_DOMAIN_SETTINGS: 'Access to custom domain configuration',
	LOGS_BASE: 'Access to base logs functionality',
	OLD_LOGS_EXPLORER: 'Access to legacy log explorer',
	SHORTCUTS: 'Access to keyboard shortcuts and help',
	ROLES_PERMISSIONS: 'Access to roles and permissions management',
	INTEGRATIONS: 'Access to third-party integrations',
	SERVICE_TOP_LEVEL_OPERATIONS: 'Access to service operation monitoring',
	INFRASTRUCTURE_MONITORING_HOSTS: 'Access to host infrastructure monitoring',
	INFRASTRUCTURE_MONITORING_KUBERNETES: 'Access to Kubernetes monitoring',
	MESSAGING_QUEUES_CELERY_TASK: 'Access to Celery task queue monitoring',
	MESSAGING_QUEUES_OVERVIEW: 'Access to messaging queue overview',
	METRICS_EXPLORER: 'Access to metrics exploration and analysis',
	METRICS_EXPLORER_EXPLORER: 'Access to advanced metrics exploration',
	METRICS_EXPLORER_VIEWS: 'Access to saved metrics views',
	API_MONITORING: 'Access to API performance monitoring',
	WORKSPACE_ACCESS_RESTRICTED: 'Access to workspace restriction page',
	METRICS_EXPLORER_BASE: 'Access to base metrics functionality',
	INFRASTRUCTURE_MONITORING_BASE: 'Access to base infrastructure monitoring',
	API_MONITORING_BASE: 'Access to base API monitoring functionality',
	MESSAGING_QUEUES_BASE: 'Access to base messaging queue functionality',
};

// Default/initial permissions - these are used as fallback and initial state
export const defaultComponentPermission: Record<ComponentTypes, ROLES[]> = {
	current_org_settings: ['ADMIN'],
	invite_members: ['ADMIN'],
	create_new_dashboards: ['ADMIN', 'EDITOR'],
	import_dashboard: ['ADMIN', 'EDITOR'],
	export_dashboard: ['ADMIN', 'EDITOR', 'VIEWER'],
	add_new_alert: ['ADMIN', 'EDITOR'],
	add_new_channel: ['ADMIN'],
	set_retention_period: ['ADMIN'],
	action: ['ADMIN', 'EDITOR'],
	save_layout: ['ADMIN', 'EDITOR', 'AUTHOR'],
	edit_dashboard: ['ADMIN', 'EDITOR', 'AUTHOR'],
	delete_widget: ['ADMIN', 'EDITOR', 'AUTHOR'],
	new_dashboard: ['ADMIN', 'EDITOR'],
	new_alert_action: ['ADMIN'],
	edit_widget: ['ADMIN', 'EDITOR'],
	add_panel: ['ADMIN', 'EDITOR', 'AUTHOR'],
	page_pipelines: ['ADMIN', 'EDITOR'],
	edit_locked_dashboard: ['ADMIN', 'AUTHOR'],
	add_panel_locked_dashboard: ['ADMIN', 'AUTHOR'],
};

export const defaultRoutePermission: Record<keyof typeof ROUTES, ROLES[]> = {
	HOME: ['ADMIN', 'EDITOR', 'VIEWER'],
	ALERTS_NEW: ['ADMIN', 'EDITOR'],
	ORG_SETTINGS: ['ADMIN'],
	MY_SETTINGS: ['ADMIN', 'EDITOR', 'VIEWER'],
	SERVICE_MAP: ['ADMIN', 'EDITOR', 'VIEWER'],
	ALL_CHANNELS: ['ADMIN', 'EDITOR', 'VIEWER'],
	INGESTION_SETTINGS: ['ADMIN', 'EDITOR', 'VIEWER'],
	ALL_DASHBOARD: ['ADMIN', 'EDITOR', 'VIEWER'],
	MESSAGING_QUEUES_KAFKA: ['ADMIN', 'EDITOR', 'VIEWER'],
	MESSAGING_QUEUES_KAFKA_DETAIL: ['ADMIN', 'EDITOR', 'VIEWER'],
	ALL_ERROR: ['ADMIN', 'EDITOR', 'VIEWER'],
	APPLICATION: ['ADMIN', 'EDITOR', 'VIEWER'],
	CHANNELS_EDIT: ['ADMIN'],
	CHANNELS_NEW: ['ADMIN'],
	DASHBOARD: ['ADMIN', 'EDITOR', 'VIEWER'],
	DASHBOARD_WIDGET: ['ADMIN', 'EDITOR', 'VIEWER'],
	EDIT_ALERTS: ['ADMIN', 'EDITOR'],
	ERROR_DETAIL: ['ADMIN', 'EDITOR', 'VIEWER'],
	HOME_PAGE: ['ADMIN', 'EDITOR', 'VIEWER'],
	LIST_ALL_ALERT: ['ADMIN', 'EDITOR', 'VIEWER'],
	ALERT_HISTORY: ['ADMIN', 'EDITOR', 'VIEWER'],
	ALERT_OVERVIEW: ['ADMIN', 'EDITOR', 'VIEWER'],
	LOGIN: ['ADMIN', 'EDITOR', 'VIEWER'],
	NOT_FOUND: ['ADMIN', 'VIEWER', 'EDITOR'],
	PASSWORD_RESET: ['ADMIN', 'EDITOR', 'VIEWER'],
	SERVICE_METRICS: ['ADMIN', 'EDITOR', 'VIEWER'],
	SETTINGS: ['ADMIN', 'EDITOR', 'VIEWER'],
	SIGN_UP: ['ADMIN', 'EDITOR', 'VIEWER'],
	TRACES_EXPLORER: ['ADMIN', 'EDITOR', 'VIEWER'],
	TRACE: ['ADMIN', 'EDITOR', 'VIEWER'],
	TRACE_DETAIL: ['ADMIN', 'EDITOR', 'VIEWER'],
	UN_AUTHORIZED: ['ADMIN', 'EDITOR', 'VIEWER'],
	USAGE_EXPLORER: ['ADMIN', 'EDITOR', 'VIEWER'],
	VERSION: ['ADMIN', 'EDITOR', 'VIEWER'],
	LOGS: ['ADMIN', 'EDITOR', 'VIEWER'],
	LOGS_EXPLORER: ['ADMIN', 'EDITOR', 'VIEWER'],
	LIVE_LOGS: ['ADMIN', 'EDITOR', 'VIEWER'],
	LIST_LICENSES: ['ADMIN'],
	LOGS_INDEX_FIELDS: ['ADMIN', 'EDITOR', 'VIEWER'],
	LOGS_PIPELINES: ['ADMIN', 'EDITOR', 'VIEWER'],
	TRACE_EXPLORER: ['ADMIN', 'EDITOR', 'VIEWER'],
	GET_STARTED: ['ADMIN', 'EDITOR'],
	ONBOARDING: ['ADMIN'],
	GET_STARTED_WITH_CLOUD: ['ADMIN', 'EDITOR'],
	GET_STARTED_APPLICATION_MONITORING: ['ADMIN', 'EDITOR', 'VIEWER'],
	GET_STARTED_INFRASTRUCTURE_MONITORING: ['ADMIN', 'EDITOR', 'VIEWER'],
	GET_STARTED_LOGS_MANAGEMENT: ['ADMIN', 'EDITOR', 'VIEWER'],
	GET_STARTED_AWS_MONITORING: ['ADMIN', 'EDITOR', 'VIEWER'],
	GET_STARTED_AZURE_MONITORING: ['ADMIN', 'EDITOR', 'VIEWER'],
	WORKSPACE_LOCKED: ['ADMIN', 'EDITOR', 'VIEWER'],
	WORKSPACE_SUSPENDED: ['ADMIN', 'EDITOR', 'VIEWER'],
	BILLING: ['ADMIN'],
	SUPPORT: ['ADMIN', 'EDITOR', 'VIEWER'],
	SOMETHING_WENT_WRONG: ['ADMIN', 'EDITOR', 'VIEWER'],
	LOGS_SAVE_VIEWS: ['ADMIN', 'EDITOR', 'VIEWER'],
	TRACES_SAVE_VIEWS: ['ADMIN', 'EDITOR', 'VIEWER'],
	TRACES_FUNNELS: ['ADMIN', 'EDITOR', 'VIEWER'],
	TRACES_FUNNELS_DETAIL: ['ADMIN', 'EDITOR', 'VIEWER'],
	API_KEYS: ['ADMIN'],
	CUSTOM_DOMAIN_SETTINGS: ['ADMIN'],
	LOGS_BASE: ['ADMIN', 'EDITOR', 'VIEWER'],
	OLD_LOGS_EXPLORER: ['ADMIN', 'EDITOR', 'VIEWER'],
	SHORTCUTS: ['ADMIN', 'EDITOR', 'VIEWER'],
	ROLES_PERMISSIONS: ['ADMIN'],
	INTEGRATIONS: ['ADMIN', 'EDITOR', 'VIEWER'],
	SERVICE_TOP_LEVEL_OPERATIONS: ['ADMIN', 'EDITOR', 'VIEWER'],
	INFRASTRUCTURE_MONITORING_HOSTS: ['ADMIN', 'EDITOR', 'VIEWER'],
	INFRASTRUCTURE_MONITORING_KUBERNETES: ['ADMIN', 'EDITOR', 'VIEWER'],
	MESSAGING_QUEUES_CELERY_TASK: ['ADMIN', 'EDITOR', 'VIEWER'],
	MESSAGING_QUEUES_OVERVIEW: ['ADMIN', 'EDITOR', 'VIEWER'],
	METRICS_EXPLORER: ['ADMIN', 'EDITOR', 'VIEWER'],
	METRICS_EXPLORER_EXPLORER: ['ADMIN', 'EDITOR', 'VIEWER'],
	METRICS_EXPLORER_VIEWS: ['ADMIN', 'EDITOR', 'VIEWER'],
	API_MONITORING: ['ADMIN', 'EDITOR', 'VIEWER'],
	WORKSPACE_ACCESS_RESTRICTED: ['ADMIN', 'EDITOR', 'VIEWER'],
	METRICS_EXPLORER_BASE: ['ADMIN', 'EDITOR', 'VIEWER'],
	INFRASTRUCTURE_MONITORING_BASE: ['ADMIN', 'EDITOR', 'VIEWER'],
	API_MONITORING_BASE: ['ADMIN', 'EDITOR', 'VIEWER'],
	MESSAGING_QUEUES_BASE: ['ADMIN', 'EDITOR', 'VIEWER'],
};

// Note: Store-dependent functions (getComponentPermission, getRoutePermission, componentPermission, routePermission)
// are available in './storeHelpers' and should be imported directly from there when needed
// to avoid circular dependencie